### ISSUE TITLE
ModuleNotFoundError: No module named 'baseline_configs'

### ISSUE THREAD

**Issue by nnsriram97** [allenai/ai2thor-rearrangement#5]
I'm trying to run training code for the provided baseline model. 
`allenact -o rearrange_out -b . baseline_configs/one_phase/one_phase_rgb_resnet_dagger.py `

But I face this error. Any idea why this occurs even after providing allenact -b ./ (which contains baseline_configs)?
```
03/23 21:25:23 ERROR: Uncaught exception:	[system.py: 140]
Traceback (most recent call last):
...
  File "/path/to/anaconda3/envs/ai2thor/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'baseline_configs'
```

**Comment by mattdeitke** [comment]
Are you in the root of the `ai2thor-rearrangement` directory? That is, if you run `ls -d */` do you see a folder named `baseline_configs`?

**Comment by nnsriram97** [comment]
Yes, I'm in the root folder of ai2thor and I see `baseline_configs` by running `ls -d`. Just executing the file using python `python baseline_configs/one_phase/one_phase_rgb_resnet_dagger.py` does not produce any error after adding `sys.path.append('./')`  in the code but there's no output by running using python

**Comment by Lucaweihs** [comment]
Hi @nnsriram97,

Can you try adding the `ai2thor-rearrangement` directory to your python path? I.e.

```bash
cd PATH/TO/ai2thor-rearrangement
export PYTHONPATH=$PYTHONPATH:$PWD
```

**Comment by nnsriram97** [comment]
Hi @Lucaweihs ,

Thanks! adding the `ai2thor-rearrangement` directory to `PYTHONPATH` does the trick.
